/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2_ahorcado;

import java.awt.Color;
import javax.swing.JOptionPane;

public class AhorcadoUI extends javax.swing.JFrame {

    private int ronda = 1, rondaMax = 5, numJug = 1, fallos = 0, fallomax = 6, fallosjug2 = 0;
    private Juego juego = new Juego();
    private Jugadores jug1 = new Jugadores();
    private Jugadores jug2 = new Jugadores();

    //Colores de los botones
    private Color background = new Color(236, 239, 241);
    private Color ratonExit = new Color(102, 102, 102);

    //Mensaje emergente
    private final JOptionPane men = new JOptionPane();

    public AhorcadoUI() {
        initComponents();
        //Color paneles
        //this.jPanel_menu.setBackground(new Color(0,0,0,128));

        //Imagen del ahorcado
        this.jLabel_soga.setVisible(false);
        this.jLabel_cabeza.setVisible(false);
        this.jLabel_brazoDer.setVisible(false);
        this.jLabel_brazoIzq.setVisible(false);
        this.jLabel_piernaDer.setVisible(false);
        this.jLabel_piernaIzq.setVisible(false);
        this.jLabel_soga1.setVisible(false);
        this.jLabel_cabeza1.setVisible(false);
        this.jLabel_brazoDer1.setVisible(false);
        this.jLabel_brazoIzq1.setVisible(false);
        this.jLabel_piernaDer1.setVisible(false);
        this.jLabel_piernaIzq1.setVisible(false);

        //Paneles desactivados
        this.jPanel_jugadores.setVisible(false);
        this.jPanel_Jugador1.setVisible(false);
        this.jPanel_Jugador3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_nuevaPartida = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField_nombreJug = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_textoAdiv = new javax.swing.JTextField();
        jDialog_nuevaRonda = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nombreJug1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_textoAdiv1 = new javax.swing.JTextField();
        jPanel_fondo = new javax.swing.JPanel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_Minimizar = new javax.swing.JLabel();
        jPanel_Jugador1 = new javax.swing.JPanel();
        jLabel_soga = new javax.swing.JLabel();
        jLabel_cabeza = new javax.swing.JLabel();
        jLabel_brazoDer = new javax.swing.JLabel();
        jLabel_brazoIzq = new javax.swing.JLabel();
        jLabel_piernaDer = new javax.swing.JLabel();
        jLabel_piernaIzq = new javax.swing.JLabel();
        jTextField_palabra = new javax.swing.JTextField();
        jLabel_palabra = new javax.swing.JLabel();
        jLabel_palabra1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_fallos = new javax.swing.JTextArea();
        jPanel_Jugador3 = new javax.swing.JPanel();
        jLabel_soga1 = new javax.swing.JLabel();
        jLabel_cabeza1 = new javax.swing.JLabel();
        jLabel_brazoDer1 = new javax.swing.JLabel();
        jLabel_brazoIzq1 = new javax.swing.JLabel();
        jLabel_piernaDer1 = new javax.swing.JLabel();
        jLabel_piernaIzq1 = new javax.swing.JLabel();
        jTextField_palabra1 = new javax.swing.JTextField();
        jLabel_palabra2 = new javax.swing.JLabel();
        jLabel_palabra3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_fallos1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel_menu = new javax.swing.JPanel();
        jButton_Iniciar = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jButton_ronda = new javax.swing.JButton();
        jButton_Finpartida = new javax.swing.JButton();
        jPanel_jugadores = new javax.swing.JPanel();
        jPanel_Info_jug1 = new javax.swing.JPanel();
        jLabel_avatar1 = new javax.swing.JLabel();
        jLabel_nombreJug1 = new javax.swing.JLabel();
        jLabel_perdido = new javax.swing.JLabel();
        jLabel_ronda = new javax.swing.JLabel();
        jButton_comprobar1 = new javax.swing.JButton();
        jTextField_letra2 = new javax.swing.JTextField();
        jLabel_ganado2 = new javax.swing.JLabel();
        jLabel_resulGan = new javax.swing.JLabel();
        jLabel_resulPer = new javax.swing.JLabel();
        jLabel_numRonda = new javax.swing.JLabel();
        jPanel_Info_jug2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_avatar2 = new javax.swing.JLabel();
        jLabel_nombreJug2 = new javax.swing.JLabel();
        jLabel_ganado1 = new javax.swing.JLabel();
        jLabel_perdido1 = new javax.swing.JLabel();
        jTextField_letra1 = new javax.swing.JTextField();
        jLabel_ronda1 = new javax.swing.JLabel();
        jButton_comprobar2 = new javax.swing.JButton();
        jLabel_resulGan1 = new javax.swing.JLabel();
        jLabel_resulPer1 = new javax.swing.JLabel();
        jLabel_numRonda1 = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        jDialog_nuevaPartida.setTitle("Nueva Partida");
        jDialog_nuevaPartida.setBackground(new java.awt.Color(96, 125, 139));
        jDialog_nuevaPartida.setMinimumSize(new java.awt.Dimension(346, 453));
        jDialog_nuevaPartida.setModal(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del Jugador 1");

        jTextField_nombreJug.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_nombreJug.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_nombreJug.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nombreJug.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nombreJug.setBorder(null);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Aceptar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Palabra para adivinar");

        jTextField_textoAdiv.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_textoAdiv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_textoAdiv.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_textoAdiv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_textoAdiv.setBorder(null);

        javax.swing.GroupLayout jDialog_nuevaPartidaLayout = new javax.swing.GroupLayout(jDialog_nuevaPartida.getContentPane());
        jDialog_nuevaPartida.getContentPane().setLayout(jDialog_nuevaPartidaLayout);
        jDialog_nuevaPartidaLayout.setHorizontalGroup(
            jDialog_nuevaPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_nuevaPartidaLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jDialog_nuevaPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jTextField_nombreJug)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_textoAdiv)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jDialog_nuevaPartidaLayout.setVerticalGroup(
            jDialog_nuevaPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_nuevaPartidaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_nombreJug, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField_textoAdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jDialog_nuevaRonda.setTitle("Siguiente Ronda");
        jDialog_nuevaRonda.setBackground(new java.awt.Color(96, 125, 139));
        jDialog_nuevaRonda.setMinimumSize(new java.awt.Dimension(346, 453));
        jDialog_nuevaRonda.setModal(true);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre del Jugador 1");

        jTextField_nombreJug1.setEditable(false);
        jTextField_nombreJug1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_nombreJug1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_nombreJug1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nombreJug1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nombreJug1.setBorder(null);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Aceptar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Palabra para adivinar");

        jTextField_textoAdiv1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_textoAdiv1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_textoAdiv1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_textoAdiv1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_textoAdiv1.setBorder(null);

        javax.swing.GroupLayout jDialog_nuevaRondaLayout = new javax.swing.GroupLayout(jDialog_nuevaRonda.getContentPane());
        jDialog_nuevaRonda.getContentPane().setLayout(jDialog_nuevaRondaLayout);
        jDialog_nuevaRondaLayout.setHorizontalGroup(
            jDialog_nuevaRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_nuevaRondaLayout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(jDialog_nuevaRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jTextField_nombreJug1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_textoAdiv1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jDialog_nuevaRondaLayout.setVerticalGroup(
            jDialog_nuevaRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_nuevaRondaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_nombreJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField_textoAdiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1061, 657));
        setMinimumSize(new java.awt.Dimension(1061, 657));
        setName("AhorcadoUI"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1061, 657));
        setResizable(false);
        setSize(new java.awt.Dimension(1061, 657));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_fondo.setBackground(new java.awt.Color(38, 50, 56));
        jPanel_fondo.setMaximumSize(new java.awt.Dimension(1061, 657));
        jPanel_fondo.setMinimumSize(new java.awt.Dimension(1061, 657));
        jPanel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Exit.setForeground(new java.awt.Color(102, 204, 255));
        jLabel_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Cerrar Gris ventana-48.png"))); // NOI18N
        jLabel_Exit.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseExited(evt);
            }
        });
        jPanel_fondo.add(jLabel_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, -2, -1, -1));

        jLabel_Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Minimizar la ventana-48.png"))); // NOI18N
        jLabel_Minimizar.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabel_Minimizar.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabel_Minimizar.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizarMouseExited(evt);
            }
        });
        jPanel_fondo.add(jLabel_Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, -2, -1, -1));

        jPanel_Jugador1.setBackground(new java.awt.Color(176, 190, 197));
        jPanel_Jugador1.setMaximumSize(new java.awt.Dimension(630, 330));
        jPanel_Jugador1.setMinimumSize(new java.awt.Dimension(630, 330));
        jPanel_Jugador1.setRequestFocusEnabled(false);
        jPanel_Jugador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_soga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_soga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Soga-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_soga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel_cabeza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cabeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cabeza-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_cabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 146, -1, -1));

        jLabel_brazoDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_brazoDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Brazo derecho-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_brazoDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel_brazoIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_brazoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Brazo izquierdo-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_brazoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 200, -1, -1));

        jLabel_piernaDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_piernaDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pierna derecha-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_piernaDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel_piernaIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_piernaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pierna izquierda-1.png"))); // NOI18N
        jPanel_Jugador1.add(jLabel_piernaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 260, -1, -1));

        jTextField_palabra.setEditable(false);
        jTextField_palabra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_palabra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_palabra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_palabra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_palabra.setBorder(null);
        jPanel_Jugador1.add(jTextField_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 320, 30));

        jLabel_palabra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_palabra.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabra.setText("Letras incorrectas");
        jPanel_Jugador1.add(jLabel_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel_palabra1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_palabra1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_palabra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabra1.setText("Palabra ha adivinar");
        jPanel_Jugador1.add(jLabel_palabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea_fallos.setEditable(false);
        jTextArea_fallos.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea_fallos.setColumns(20);
        jTextArea_fallos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_fallos.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_fallos.setLineWrap(true);
        jTextArea_fallos.setRows(5);
        jTextArea_fallos.setBorder(null);
        jScrollPane1.setViewportView(jTextArea_fallos);

        jPanel_Jugador1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jPanel_fondo.add(jPanel_Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 630, 328));

        jPanel_Jugador3.setBackground(new java.awt.Color(176, 190, 197));
        jPanel_Jugador3.setMaximumSize(new java.awt.Dimension(630, 330));
        jPanel_Jugador3.setMinimumSize(new java.awt.Dimension(630, 330));
        jPanel_Jugador3.setRequestFocusEnabled(false);
        jPanel_Jugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_soga1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_soga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Soga-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_soga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel_cabeza1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cabeza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cabeza-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_cabeza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 146, -1, -1));

        jLabel_brazoDer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_brazoDer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Brazo derecho-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_brazoDer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel_brazoIzq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_brazoIzq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Brazo izquierdo-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_brazoIzq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 200, -1, -1));

        jLabel_piernaDer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_piernaDer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pierna derecha-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_piernaDer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel_piernaIzq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_piernaIzq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pierna izquierda-1.png"))); // NOI18N
        jPanel_Jugador3.add(jLabel_piernaIzq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 260, -1, -1));

        jTextField_palabra1.setEditable(false);
        jTextField_palabra1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_palabra1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_palabra1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_palabra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_palabra1.setBorder(null);
        jPanel_Jugador3.add(jTextField_palabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 320, 30));

        jLabel_palabra2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_palabra2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_palabra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabra2.setText("Letras incorrectas");
        jPanel_Jugador3.add(jLabel_palabra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel_palabra3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_palabra3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_palabra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabra3.setText("Palabra ha adivinar");
        jPanel_Jugador3.add(jLabel_palabra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea_fallos1.setEditable(false);
        jTextArea_fallos1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea_fallos1.setColumns(20);
        jTextArea_fallos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_fallos1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_fallos1.setLineWrap(true);
        jTextArea_fallos1.setRows(5);
        jTextArea_fallos1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea_fallos1);

        jPanel_Jugador3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Jugador3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 630, 20));

        jPanel_fondo.add(jPanel_Jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 630, 328));

        jPanel_menu.setBackground(new java.awt.Color(144, 164, 174));
        jPanel_menu.setMaximumSize(new java.awt.Dimension(200, 657));
        jPanel_menu.setMinimumSize(new java.awt.Dimension(200, 657));
        jPanel_menu.setName("Menu"); // NOI18N
        jPanel_menu.setPreferredSize(new java.awt.Dimension(200, 657));

        jButton_Iniciar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Iniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Iniciar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Iniciar.setText("<html>Nueva<br>Partida</html>");
        jButton_Iniciar.setBorder(null);
        jButton_Iniciar.setBorderPainted(false);
        jButton_Iniciar.setFocusPainted(false);
        jButton_Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_IniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_IniciarMouseExited(evt);
            }
        });
        jButton_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IniciarActionPerformed(evt);
            }
        });

        jLabel_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Juego del Ahorcado");

        jButton_ronda.setBackground(new java.awt.Color(102, 102, 102));
        jButton_ronda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ronda.setForeground(new java.awt.Color(0, 0, 0));
        jButton_ronda.setText("<html>Siguiente<br>Ronda</html>");
        jButton_ronda.setBorder(null);
        jButton_ronda.setBorderPainted(false);
        jButton_ronda.setEnabled(false);
        jButton_ronda.setFocusPainted(false);
        jButton_ronda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_rondaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_rondaMouseExited(evt);
            }
        });
        jButton_ronda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rondaActionPerformed(evt);
            }
        });

        jButton_Finpartida.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Finpartida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Finpartida.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Finpartida.setText("<html>Cerrar<br>Partida</html>");
        jButton_Finpartida.setBorder(null);
        jButton_Finpartida.setBorderPainted(false);
        jButton_Finpartida.setEnabled(false);
        jButton_Finpartida.setFocusPainted(false);
        jButton_Finpartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_FinpartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_FinpartidaMouseExited(evt);
            }
        });
        jButton_Finpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FinpartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel_titulo)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Finpartida)
                    .addComponent(jButton_Iniciar)
                    .addComponent(jButton_ronda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo)
                .addGap(79, 79, 79)
                .addComponent(jButton_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ronda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Finpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jPanel_fondo.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel_jugadores.setBackground(new java.awt.Color(96, 125, 139));
        jPanel_jugadores.setMaximumSize(new java.awt.Dimension(240, 660));
        jPanel_jugadores.setMinimumSize(new java.awt.Dimension(240, 660));
        jPanel_jugadores.setName("Jugadores"); // NOI18N
        jPanel_jugadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Info_jug1.setBackground(new java.awt.Color(96, 125, 139));
        jPanel_Info_jug1.setPreferredSize(new java.awt.Dimension(240, 328));
        jPanel_Info_jug1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_avatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatar 1v2.png"))); // NOI18N
        jPanel_Info_jug1.add(jLabel_avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 110));

        jLabel_nombreJug1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_nombreJug1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_nombreJug1.setText("Jugador 1");
        jPanel_Info_jug1.add(jLabel_nombreJug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        jLabel_perdido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_perdido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_perdido.setText("Perdido:");
        jPanel_Info_jug1.add(jLabel_perdido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel_ronda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ronda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ronda.setText("Ronda ");
        jPanel_Info_jug1.add(jLabel_ronda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButton_comprobar1.setBackground(new java.awt.Color(102, 102, 102));
        jButton_comprobar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_comprobar1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_comprobar1.setText("Enviar");
        jButton_comprobar1.setActionCommand("Enviar_jug1");
        jButton_comprobar1.setBorder(null);
        jButton_comprobar1.setBorderPainted(false);
        jButton_comprobar1.setFocusPainted(false);
        jButton_comprobar1.setName("enviar_jug1"); // NOI18N
        jButton_comprobar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_comprobar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_comprobar1MouseExited(evt);
            }
        });
        jButton_comprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprobar1ActionPerformed(evt);
            }
        });
        jPanel_Info_jug1.add(jButton_comprobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 60, 30));

        jTextField_letra2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_letra2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_letra2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_letra2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_letra2.setBorder(null);
        jPanel_Info_jug1.add(jTextField_letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 30));

        jLabel_ganado2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ganado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ganado2.setText("Ganado:");
        jPanel_Info_jug1.add(jLabel_ganado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel_resulGan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_resulGan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resulGan.setText("0");
        jLabel_resulGan.setPreferredSize(new java.awt.Dimension(34, 20));
        jPanel_Info_jug1.add(jLabel_resulGan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel_resulPer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_resulPer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resulPer.setText("0");
        jLabel_resulPer.setPreferredSize(new java.awt.Dimension(34, 20));
        jPanel_Info_jug1.add(jLabel_resulPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel_numRonda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_numRonda.setText("1");
        jPanel_Info_jug1.add(jLabel_numRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        jPanel_jugadores.add(jPanel_Info_jug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel_Info_jug2.setBackground(new java.awt.Color(96, 125, 139));
        jPanel_Info_jug2.setPreferredSize(new java.awt.Dimension(240, 328));
        jPanel_Info_jug2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Info_jug2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 240, 20));

        jLabel_avatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatar 2v2.png"))); // NOI18N
        jPanel_Info_jug2.add(jLabel_avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 110));

        jLabel_nombreJug2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_nombreJug2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_nombreJug2.setText("Jugador 2");
        jPanel_Info_jug2.add(jLabel_nombreJug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        jLabel_ganado1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ganado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ganado1.setText("Ganado:");
        jPanel_Info_jug2.add(jLabel_ganado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel_perdido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_perdido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_perdido1.setText("Perdido:");
        jPanel_Info_jug2.add(jLabel_perdido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jTextField_letra1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_letra1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_letra1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_letra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_letra1.setBorder(null);
        jPanel_Info_jug2.add(jTextField_letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 30));

        jLabel_ronda1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ronda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ronda1.setText("Ronda ");
        jPanel_Info_jug2.add(jLabel_ronda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButton_comprobar2.setBackground(new java.awt.Color(102, 102, 102));
        jButton_comprobar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_comprobar2.setForeground(new java.awt.Color(0, 0, 0));
        jButton_comprobar2.setText("Enviar");
        jButton_comprobar2.setActionCommand("Enviar_jug2");
        jButton_comprobar2.setBorder(null);
        jButton_comprobar2.setBorderPainted(false);
        jButton_comprobar2.setEnabled(false);
        jButton_comprobar2.setFocusPainted(false);
        jButton_comprobar2.setName("enviar_jug2"); // NOI18N
        jButton_comprobar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_comprobar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_comprobar2MouseExited(evt);
            }
        });
        jButton_comprobar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprobar1ActionPerformed(evt);
            }
        });
        jPanel_Info_jug2.add(jButton_comprobar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 60, 30));

        jLabel_resulGan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_resulGan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resulGan1.setText("0");
        jLabel_resulGan1.setPreferredSize(new java.awt.Dimension(34, 20));
        jPanel_Info_jug2.add(jLabel_resulGan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel_resulPer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_resulPer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resulPer1.setText("0");
        jLabel_resulPer1.setPreferredSize(new java.awt.Dimension(34, 20));
        jPanel_Info_jug2.add(jLabel_resulPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel_numRonda1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_numRonda1.setText("1");
        jPanel_Info_jug2.add(jLabel_numRonda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        jPanel_jugadores.add(jPanel_Info_jug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jPanel_fondo.add(jPanel_jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 240, 660));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background-opera.jpg"))); // NOI18N
        jLabel_fondo.setMaximumSize(new java.awt.Dimension(1061, 660));
        jLabel_fondo.setMinimumSize(new java.awt.Dimension(1061, 660));
        jLabel_fondo.setPreferredSize(new java.awt.Dimension(1061, 660));
        jPanel_fondo.add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1061, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseEntered
        this.jLabel_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Cerrar ventana-48.png")));
    }//GEN-LAST:event_jLabel_ExitMouseEntered

    private void jLabel_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseExited
        jLabel_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Cerrar Gris ventana-48.png")));
    }//GEN-LAST:event_jLabel_ExitMouseExited

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_ExitMouseClicked

    private void jLabel_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizarMouseEntered
        jLabel_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Minimizar la ventana Filled-48.png")));
    }//GEN-LAST:event_jLabel_MinimizarMouseEntered

    private void jLabel_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizarMouseExited
        jLabel_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-Minimizar la ventana-48.png")));
    }//GEN-LAST:event_jLabel_MinimizarMouseExited

    private void jLabel_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizarMouseClicked

    private void jButton_IniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IniciarMouseEntered
        this.jButton_Iniciar.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_jButton_IniciarMouseEntered

    private void jButton_IniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IniciarMouseExited
        this.jButton_Iniciar.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButton_IniciarMouseExited

    private void jButton_comprobar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_comprobar1MouseEntered
        this.jButton_comprobar1.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_jButton_comprobar1MouseEntered

    private void jButton_comprobar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_comprobar1MouseExited
        this.jButton_comprobar1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButton_comprobar1MouseExited

    private void jButton_comprobar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_comprobar2MouseEntered
        this.jButton_comprobar2.setBackground(new Color(236, 239, 241));
    }//GEN-LAST:event_jButton_comprobar2MouseEntered

    private void jButton_comprobar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_comprobar2MouseExited
        this.jButton_comprobar2.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButton_comprobar2MouseExited

    private void jButton_rondaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_rondaMouseEntered
        this.jButton_ronda.setBackground(background);
    }//GEN-LAST:event_jButton_rondaMouseEntered

    private void jButton_rondaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_rondaMouseExited
        this.jButton_ronda.setBackground(this.ratonExit);
    }//GEN-LAST:event_jButton_rondaMouseExited

    private void jButton_FinpartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_FinpartidaMouseEntered
        this.jButton_Finpartida.setBackground(background);
    }//GEN-LAST:event_jButton_FinpartidaMouseEntered

    private void jButton_FinpartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_FinpartidaMouseExited
        this.jButton_Finpartida.setBackground(this.ratonExit);
    }//GEN-LAST:event_jButton_FinpartidaMouseExited

    private void jButton_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IniciarActionPerformed
        this.jDialog_nuevaPartida.setLocationRelativeTo(this);
        this.jDialog_nuevaPartida.setVisible(true);
    }//GEN-LAST:event_jButton_IniciarActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        this.jButton1.setBackground(background);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        this.jButton1.setBackground(this.ratonExit);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String palabra = "";

        if (this.numJug == 1) {
            this.jug1.setNombreJugador(this.jTextField_nombreJug.getText());
            this.jug1.setPalabraAdivinar(this.jTextField_textoAdiv.getText());
            this.juego.setJugador1(jug1);
            this.jLabel_nombreJug1.setText(this.jug1.getNombreJugador());
            palabra = this.jug1.getPalabraAdivinar();

            palabra = ReemplazarPalabra(palabra);
            this.jTextField_palabra1.setText(palabra);

            this.jTextField_nombreJug.setText("");
            this.jTextField_textoAdiv.setText("");
            this.jButton_Iniciar.setText("<html>Siguiente<br>Jugador</html>");
            this.jLabel1.setText("Nombre del Jugador 2");
            this.jLabel_nombreJug1.setText(this.jug1.getNombreJugador());
            this.numJug = 2;
        } else {
            this.jug2.setNombreJugador(this.jTextField_nombreJug.getText());
            this.jug2.setPalabraAdivinar(this.jTextField_textoAdiv.getText());
            this.juego.setJugador2(jug2);
            palabra = this.jug2.getPalabraAdivinar();

            palabra = ReemplazarPalabra(palabra);
            this.jTextField_palabra.setText(palabra);
            this.jLabel_nombreJug2.setText(this.jug2.getNombreJugador());
            this.jPanel_jugadores.setVisible(false);
            this.jPanel_Jugador1.setVisible(false);
            this.jPanel_Jugador3.setVisible(false);
            this.jButton1.setText("Siguiente Jugador");
            this.jLabel_nombreJug2.setText(this.jug2.getNombreJugador());
            this.jButton_Iniciar.setText("<html>Nueva<br>Partida</html>");
            this.jLabel1.setText("Nombre del Jugador 1");
            this.jButton_Iniciar.setEnabled(false);
            this.jPanel_jugadores.setVisible(true);
            this.jPanel_Jugador1.setVisible(true);
            this.jPanel_Jugador3.setVisible(true);
            this.numJug = 1;
            this.jButton_Finpartida.setEnabled(true);
        }
        this.jDialog_nuevaPartida.setVisible(false);
        this.men.showMessageDialog(null, "Jugador Guardado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_FinpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FinpartidaActionPerformed
        this.men.showMessageDialog(null, "Cerrar Juego", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButton_FinpartidaActionPerformed

    private void jButton_comprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprobar1ActionPerformed
        String result = "", letra = "";
        int ganado, perdido;
        boolean perdidojug1 = false, perdidojug2 = false;

        if (evt.getActionCommand().compareTo("Enviar_jug1") == 0) {
            if (this.jTextField_letra2.getText().compareTo("") != 0) {

                if (this.juego.LetraDisponible(this.jTextField_letra2.getText()/*.substring(0)*/, this.jug1) != -1) {
                    result = this.juego.CambiarLetra(this.jTextField_letra2.getText()/*.substring(0)*/, this.jTextField_palabra.getText(), jug1);
                    this.jTextField_palabra.setText(result);

                    //Comprobar si ha acertado la palabra
                    if (this.juego.AdivinarPalabra(result, jug1) == true) {
                        this.men.showMessageDialog(null, "El Jugador 1 ha Ganado", "Ganador", JOptionPane.INFORMATION_MESSAGE);
                        this.jButton_comprobar1.setEnabled(false);
                        this.jButton_comprobar2.setEnabled(false);

                        ganado = Integer.parseInt(this.jLabel_resulGan.getText());
                        ganado++;
                        this.jLabel_resulGan.setText(ganado + "");

                        
                        if (this.ronda < this.rondaMax) {
                            this.men.showMessageDialog(null, "Inicia siguiente ronda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                            this.jButton_ronda.setEnabled(true);
                        }
                        else {
                            this.men.showMessageDialog(null, "Fin del Juego", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                } else {
                    letra = String.valueOf(this.jTextField_letra2.getText().charAt(0));
                    this.jTextArea_fallos.setText(this.jTextArea_fallos.getText() + letra/*this.jTextField_letra2.getText().substring(0)*/ + ", ");
                    this.fallos++;

                    if (this.fallos < this.fallomax + 1) {
                        switch (fallos) {
                            case 1: //Soga
                                this.jLabel_soga.setVisible(true);
                                break;
                            case 2:
                                this.jLabel_cabeza.setVisible(true);
                                break;
                            case 3:
                                this.jLabel_brazoDer.setVisible(true);
                                break;
                            case 4:
                                this.jLabel_brazoIzq.setVisible(true);
                                break;
                            case 5:
                                this.jLabel_piernaDer.setVisible(true);
                                break;
                            case 6:
                                this.jLabel_piernaIzq.setVisible(true);
                                perdidojug1 = true;
                                perdido = Integer.parseInt(this.jLabel_resulPer.getText());
                                perdido++;
                                this.jLabel_resulPer.setText(perdido + "");
                                this.men.showMessageDialog(null, "Has Perdido", "Jugador 1", JOptionPane.INFORMATION_MESSAGE);
                                this.jButton_comprobar1.setEnabled(false);
                                this.jButton_comprobar2.setEnabled(false);
                                
                                if (this.ronda < this.rondaMax) {
                                    this.men.showMessageDialog(null, "Inicia siguiente ronda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                    this.jButton_ronda.setEnabled(true);
                                }
                                else {
                                    this.men.showMessageDialog(null, "Fin del Juego", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                }
                                break;
                        }
                    }

                }

                if (this.juego.AdivinarPalabra(result, jug1) == false && perdidojug1 == false) {
                    //Desactivar boton del jugador 1 y activa el del jugador 2
                    this.jButton_comprobar1.setEnabled(false);
                    this.jButton_comprobar2.setEnabled(true);
                    this.men.showMessageDialog(null, "Turno al jugador 2", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                this.men.showMessageDialog(null, "Debes introducir una letra", "Jugador 1", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            if (this.jTextField_letra1.getText().compareTo("") != 0) {

                if (this.juego.LetraDisponible(this.jTextField_letra1.getText().substring(0), this.jug2) != -1) {
                    result = this.juego.CambiarLetra(this.jTextField_letra1.getText().substring(0), this.jTextField_palabra1.getText().substring(0), jug2);
                    this.jTextField_palabra1.setText(result);

                    //Comprobar si ha acertado la palabra
                    if (this.juego.AdivinarPalabra(result, jug2) == true) {
                        this.men.showMessageDialog(null, "El Jugador 2 ha Ganado", "Ganador", JOptionPane.INFORMATION_MESSAGE);
                        this.jButton_comprobar1.setEnabled(false);
                        this.jButton_comprobar2.setEnabled(false);

                        ganado = Integer.parseInt(this.jLabel_resulGan1.getText());
                        ganado++;
                        this.jLabel_resulGan1.setText(ganado + "");

                        
                        if (this.ronda < this.rondaMax) {
                            this.men.showMessageDialog(null, "Inicia siguiente ronda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                            this.jButton_ronda.setEnabled(true);
                        }
                        else {
                            this.men.showMessageDialog(null, "Fin del Juego", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                } else {
                    letra = String.valueOf(this.jTextField_letra1.getText().charAt(0));
                    this.jTextArea_fallos1.setText(this.jTextArea_fallos1.getText() + letra/*this.jTextField_letra1.getText()*/ + ", ");
                    this.fallosjug2++;

                    if (this.fallosjug2 < this.fallomax + 1) {
                        switch (this.fallosjug2) {
                            case 1: //Soga
                                this.jLabel_soga1.setVisible(true);
                                break;
                            case 2:
                                this.jLabel_cabeza1.setVisible(true);
                                break;
                            case 3:
                                this.jLabel_brazoDer1.setVisible(true);
                                break;
                            case 4:
                                this.jLabel_brazoIzq1.setVisible(true);
                                break;
                            case 5:
                                this.jLabel_piernaDer1.setVisible(true);
                                break;
                            case 6:
                                this.jLabel_piernaIzq1.setVisible(true);
                                perdido = Integer.parseInt(this.jLabel_resulPer1.getText());
                                perdido++;
                                perdidojug2 = true;
                                this.jLabel_resulPer1.setText(perdido + "");
                                this.men.showMessageDialog(null, "Has Perdido", "Jugador 2", JOptionPane.INFORMATION_MESSAGE);
                                this.jButton_comprobar1.setEnabled(false);
                                this.jButton_comprobar2.setEnabled(false);
                                
                                if (this.ronda < this.rondaMax) {
                                    this.men.showMessageDialog(null, "Inicia siguiente ronda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                    this.jButton_ronda.setEnabled(true);
                                }
                                else {
                                    this.men.showMessageDialog(null, "Inicia siguiente ronda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                }
                                break;
                        }
                    }

                }
                if (this.juego.AdivinarPalabra(result, jug2) == false && perdidojug2 == false) {
                    //Desactivar boton del jugador 1 y activa el del jugador 2
                    this.jButton_comprobar1.setEnabled(true);
                    this.jButton_comprobar2.setEnabled(false);
                    this.men.showMessageDialog(null, "Turno al jugador 1", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                this.men.showMessageDialog(null, "Debes introducir una letra", "Jugador 2", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        this.jTextField_letra2.setText("");
        this.jTextField_letra1.setText("");
    }//GEN-LAST:event_jButton_comprobar1ActionPerformed

    private void jButton_rondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rondaActionPerformed

        //Imagen del ahorcado
        this.jLabel_soga.setVisible(false);
        this.jLabel_cabeza.setVisible(false);
        this.jLabel_brazoDer.setVisible(false);
        this.jLabel_brazoIzq.setVisible(false);
        this.jLabel_piernaDer.setVisible(false);
        this.jLabel_piernaIzq.setVisible(false);
        this.jLabel_soga1.setVisible(false);
        this.jLabel_cabeza1.setVisible(false);
        this.jLabel_brazoDer1.setVisible(false);
        this.jLabel_brazoIzq1.setVisible(false);
        this.jLabel_piernaDer1.setVisible(false);
        this.jLabel_piernaIzq1.setVisible(false);
        this.jPanel_Jugador1.setVisible(false);
        this.jPanel_Jugador3.setVisible(false);

        if (this.ronda < this.rondaMax) {
            if (this.numJug == 1) {
                this.jTextField_nombreJug1.setText(this.juego.getJugador1().getNombreJugador());
            } else {
                this.jTextField_nombreJug1.setText(this.juego.getJugador2().getNombreJugador());
            }
            this.jDialog_nuevaRonda.setLocationRelativeTo(this);
            this.jDialog_nuevaRonda.setVisible(true);
        }
    }//GEN-LAST:event_jButton_rondaActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        this.jButton2.setBackground(background);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        this.jButton2.setBackground(this.ratonExit);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String palabra = "";
        if (this.numJug == 1) {
            if (this.jTextField_textoAdiv1.getText().compareTo("") != 0) {
                this.juego.getJugador1().setPalabraAdivinar(this.jTextField_textoAdiv1.getText());
                this.jDialog_nuevaRonda.setVisible(false);
                this.men.showMessageDialog(null, "Palabra Guardada", "Jugador 1", JOptionPane.INFORMATION_MESSAGE);
                this.numJug = 2;
                palabra = this.juego.getJugador1().getPalabraAdivinar();
                palabra = ReemplazarPalabra(palabra);
                this.jTextField_palabra1.setText(palabra);
                this.jTextField_palabra1.setText(palabra);
                this.jButton_ronda.setText("<html>Siguiente<br>Jugador</html>");
                this.jLabel3.setText("Nombre del Jugador 2");
            } else {
                this.men.showMessageDialog(null, "Debes introducir una palabra", "Jugador 1", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            if (this.jTextField_textoAdiv1.getText().compareTo("") != 0) {
                this.juego.getJugador2().setPalabraAdivinar(this.jTextField_textoAdiv1.getText());
                this.jDialog_nuevaRonda.setVisible(false);
                this.men.showMessageDialog(null, "Palabra Guardada", "Jugador 2", JOptionPane.INFORMATION_MESSAGE);
                this.numJug = 1;
                palabra = this.juego.getJugador2().getPalabraAdivinar();
                palabra = ReemplazarPalabra(palabra);
                this.jTextField_palabra.setText(palabra);
                this.jTextField_palabra.setText(palabra);
                this.jLabel3.setText("Nombre del Jugador 1");
                this.jButton_ronda.setText("<html>Siguiente<br>Ronda</html>");
                this.jButton_ronda.setEnabled(false);
                this.jButton_comprobar1.setEnabled(true);
                this.jTextArea_fallos.setText("");
                this.jTextArea_fallos1.setText("");
                this.jPanel_Jugador1.setVisible(true);
                this.jPanel_Jugador3.setVisible(true);
                this.ronda++;
                this.jLabel_numRonda.setText(ronda + "");
                this.jLabel_numRonda1.setText(ronda + "");

                if (this.ronda == this.rondaMax) {
                    this.jLabel_numRonda.setText("Final");
                    this.jLabel_numRonda1.setText("Final");
                    this.jButton_ronda.setEnabled(false);
                }

            } else {
                this.men.showMessageDialog(null, "Debes introducir una palabra", "Jugador 2", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        this.jTextField_textoAdiv1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AhorcadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AhorcadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AhorcadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AhorcadoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhorcadoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Finpartida;
    private javax.swing.JButton jButton_Iniciar;
    private javax.swing.JButton jButton_comprobar1;
    private javax.swing.JButton jButton_comprobar2;
    private javax.swing.JButton jButton_ronda;
    private javax.swing.JDialog jDialog_nuevaPartida;
    private javax.swing.JDialog jDialog_nuevaRonda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_Minimizar;
    private javax.swing.JLabel jLabel_avatar1;
    private javax.swing.JLabel jLabel_avatar2;
    private javax.swing.JLabel jLabel_brazoDer;
    private javax.swing.JLabel jLabel_brazoDer1;
    private javax.swing.JLabel jLabel_brazoIzq;
    private javax.swing.JLabel jLabel_brazoIzq1;
    private javax.swing.JLabel jLabel_cabeza;
    private javax.swing.JLabel jLabel_cabeza1;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_ganado1;
    private javax.swing.JLabel jLabel_ganado2;
    private javax.swing.JLabel jLabel_nombreJug1;
    private javax.swing.JLabel jLabel_nombreJug2;
    private javax.swing.JLabel jLabel_numRonda;
    private javax.swing.JLabel jLabel_numRonda1;
    private javax.swing.JLabel jLabel_palabra;
    private javax.swing.JLabel jLabel_palabra1;
    private javax.swing.JLabel jLabel_palabra2;
    private javax.swing.JLabel jLabel_palabra3;
    private javax.swing.JLabel jLabel_perdido;
    private javax.swing.JLabel jLabel_perdido1;
    private javax.swing.JLabel jLabel_piernaDer;
    private javax.swing.JLabel jLabel_piernaDer1;
    private javax.swing.JLabel jLabel_piernaIzq;
    private javax.swing.JLabel jLabel_piernaIzq1;
    private javax.swing.JLabel jLabel_resulGan;
    private javax.swing.JLabel jLabel_resulGan1;
    private javax.swing.JLabel jLabel_resulPer;
    private javax.swing.JLabel jLabel_resulPer1;
    private javax.swing.JLabel jLabel_ronda;
    private javax.swing.JLabel jLabel_ronda1;
    private javax.swing.JLabel jLabel_soga;
    private javax.swing.JLabel jLabel_soga1;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel_Info_jug1;
    private javax.swing.JPanel jPanel_Info_jug2;
    private javax.swing.JPanel jPanel_Jugador1;
    private javax.swing.JPanel jPanel_Jugador3;
    private javax.swing.JPanel jPanel_fondo;
    private javax.swing.JPanel jPanel_jugadores;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_fallos;
    private javax.swing.JTextArea jTextArea_fallos1;
    private javax.swing.JTextField jTextField_letra1;
    private javax.swing.JTextField jTextField_letra2;
    private javax.swing.JTextField jTextField_nombreJug;
    private javax.swing.JTextField jTextField_nombreJug1;
    private javax.swing.JTextField jTextField_palabra;
    private javax.swing.JTextField jTextField_palabra1;
    private javax.swing.JTextField jTextField_textoAdiv;
    private javax.swing.JTextField jTextField_textoAdiv1;
    // End of variables declaration//GEN-END:variables

    private String ReemplazarPalabra(String palabra) {
        char[] letras;

        letras = palabra.toCharArray();

        for (int i = 0; i < palabra.length(); i++) {
            letras[i] = '*';
        }

        return String.valueOf(letras);
    }
}
